# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-04 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('youtubelink', models.URLField(max_length=2000)),
                ('githublink', models.URLField(max_length=2000)),
                ('member1name', models.CharField(max_length=60)),
                ('member1reg', models.CharField(max_length=20)),
                ('member2name', models.CharField(max_length=60)),
                ('member2reg', models.CharField(max_length=20)),
                ('member3name', models.CharField(max_length=60)),
                ('member3reg', models.CharField(max_length=20)),
                ('member4name', models.CharField(max_length=60)),
                ('member4reg', models.CharField(max_length=20)),
                ('member5name', models.CharField(max_length=60)),
                ('member5reg', models.CharField(max_length=20)),
                ('member6name', models.CharField(max_length=60)),
                ('member6reg', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('youtubelink', models.URLField(max_length=2000)),
                ('githublink', models.URLField(max_length=2000)),
                ('member1name', models.CharField(max_length=60)),
                ('member1reg', models.CharField(max_length=20)),
                ('member2name', models.CharField(max_length=60)),
                ('member2reg', models.CharField(max_length=20)),
                ('member3name', models.CharField(max_length=60)),
                ('member3reg', models.CharField(max_length=20)),
                ('member4name', models.CharField(max_length=60)),
                ('member4reg', models.CharField(max_length=20)),
                ('member5name', models.CharField(max_length=60)),
                ('member5reg', models.CharField(max_length=20)),
                ('member6name', models.CharField(max_length=60)),
                ('member6reg', models.CharField(max_length=20)),
            ],
        ),
    ]
